version: '3.5'

services:
  app:
    build:
      context: ./
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'crypto_bot'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
